// --- Environment-specific Configuration ---
// This file contains configuration variables for the application.
// For production environments, this file should be generated by a CI/CD pipeline
// with values from environment variables (e.g., from Cloudflare Pages settings).
//
// IMPORTANT: Do NOT commit this file with real production values to your repository.
// Consider adding it to .gitignore if you are editing it locally with sensitive data.

window.APP_CONFIG = {
    // Replace with your actual Zitadel project Issuer URL
    ZITADEL_ISSUER: 'https://your-zitadel-issuer-url', // e.g., https://your-instance.zitadel.cloud

    // Replace with your actual Zitadel OIDC Client ID
    ZITADEL_CLIENT_ID: 'your-client-id' // e.g., 123456789012345678@my_project
};
