#!/bin/sh

# This script generates the frontend/config.js file using environment variables.
# It's intended to be run by the Cloudflare Pages build process.

# Create the frontend directory if it doesn't exist
mkdir -p frontend

# Write the config file
# The values for ZITADEL_ISSUER and ZITADEL_CLIENT_ID will be taken from
# the environment variables set in the Cloudflare Pages project settings.
echo "
// This file is generated by the build.sh script during deployment.
// Do not edit this file manually.

window.APP_CONFIG = {
    ZITADEL_ISSUER: \"${ZITADEL_ISSUER}\",
    ZITADEL_CLIENT_ID: \"${ZITADEL_CLIENT_ID}\"
};
" > frontend/config.js

echo "frontend/config.js generated successfully."
